// lib/notifications/hrefShapesFixture.ts
//
// Renders the notification-href registry into the file tovis-ios commits and
// drives its REAL deep-link parser over.
//
// The fixture carries a `probe` alongside each shape — a concrete href built by
// substituting a value for every `{…}` placeholder. Generated HERE rather than
// composed on the Swift side, because a probe composed there would be the
// client agreeing with itself again: the phone would test the href IT thinks
// the shape means, not the one web mints. This way a change to the placeholder
// syntax cannot silently produce a probe that no longer resembles a real href.

import {
  NOTIFICATION_HREF_SHAPES,
  notificationHrefShape,
  type NotificationHrefShapeDefinition,
} from './hrefShapes'

export const NOTIFICATION_HREF_FIXTURE_PATH =
  'schema/parity/notificationHrefShapes.json'

export const NOTIFICATION_HREF_IOS_FIXTURE_PATH =
  'TovisTests/Fixtures/notificationHrefShapes.json'

/**
 * Substitute a concrete value for every `{…}` placeholder.
 *
 * The values are deliberately boring (`id1`, `id2`, …) and distinct per
 * position, so a parser that grabbed the wrong path segment produces a visibly
 * wrong id rather than one that happens to look right.
 */
function probeFor(shape: string): string {
  let n = 0
  return shape.replace(/\{[^}]+\}/g, () => {
    n += 1
    return `id${n}`
  })
}

type FixtureRow = {
  shape: string
  surface: NotificationHrefShapeDefinition['surface']
  probe: string
  target: string | null
  why: string
}

function rows(): FixtureRow[] {
  return NOTIFICATION_HREF_SHAPES.map((definition) => {
    const probe = probeFor(definition.shape)
    // Guard the generator: a probe that no longer reduces to its own shape
    // means the placeholder syntax and the matcher have drifted apart, and
    // every row after it would be quietly meaningless.
    const reduced = notificationHrefShape(probe)
    if (reduced !== definition.shape) {
      throw new Error(
        `hrefShapesFixture: probe ${JSON.stringify(probe)} for ${definition.shape} ` +
          `reduces to ${String(reduced)} — the matcher and the shape syntax disagree.`,
      )
    }
    return {
      shape: definition.shape,
      surface: definition.surface,
      probe,
      // `as const` narrows each row to its own literal type, and the 'web'
      // rows have no `target` key at all — so this reads it presence-first
      // rather than assuming the union carries the property.
      target: 'target' in definition ? definition.target : null,
      why: definition.why,
    }
  })
}

/** The exact bytes of the committed fixture, trailing newline included. */
export function renderNotificationHrefFixture(): string {
  const body = {
    $comment:
      'GENERATED by `pnpm gen:notification-href-fixture` from ' +
      'lib/notifications/hrefShapes.ts. Do not hand-edit: ' +
      'lib/notifications/hrefShapes.test.ts fails when this drifts from the ' +
      'registry. tovis-ios commits the same bytes at ' +
      'TovisTests/Fixtures/notificationHrefShapes.json and drives PushDeepLink ' +
      'over every `probe`. surface: native = a real screen (not home, not nil); ' +
      'shell = the role home IS the answer; web = the phone must NOT claim it ' +
      '(parser must return nil, so the tap stays harmless).',
    shapes: rows(),
  }
  return JSON.stringify(body, null, 2) + '\n'
}
