export const lookAnalysisCopy = {
  title: 'Prepare your looks for consultations',
  intro: 'We read your published media so clients can start with questions about the look they chose. Clarify anything we could not establish, then our review team can check it.',
  adminTitle: 'Look analysis review',
  adminIntro: 'Check the image, the original reading and the professional’s answers. Corrections are recorded separately. Leave anything the image cannot establish as unknown.',
  empty: 'No looks need attention right now.',
  loading: 'Loading look analyses…',
  failed: 'We could not load or save this review. Please try again.',
  conflict: 'This reading has changed. Refresh before reviewing it again.',
  original: 'Original AI reading',
  proAnswers: 'Professional clarification',
  unknown: 'Not sure',
  answer: 'Send clarification',
  approve: 'Approve reviewed reading',
  reject: 'Do not use this reading',
  retry: 'Retry analysis',
  refresh: 'Refresh',
  saved: 'Saved.',
  frame: 'Which frame shows the finished result?',
  extensions: 'Was added hair used for this result?',
  edited: 'Was the appearance of the hair changed with a filter, editing or AI?',
  role: 'Does this media show the finished result?',
  uncertainty: 'Please clarify the uncertain details below. Your answers stay separate from the image observations until review.',
  proNotificationTitle: 'A few details about your look',
  proNotificationBody: 'Please clarify the highlighted details so we can prepare this look for client consultations.',
  adminNotificationTitle: 'Look analysis needs review',
  adminNotificationBody: 'A saved media reading needs a check. Review the image and any professional clarification.',
  statuses: { PENDING: 'Waiting for analysis', PROCESSING: 'Analysing', NEEDS_PRO: 'Needs your clarification', NEEDS_ADMIN: 'Waiting for review', READY: 'Ready for consultations', FAILED: 'Analysis needs a retry', REJECTED: 'Excluded from consultations' },
  fields: { baseLevel: 'Root / base level', lightestLevel: 'Lightest level', tone: 'Tone', technique: 'Technique', placement: 'Placement', rootBlend: 'Root blend', finish: 'Finish', dimension: 'Dimension' },
} as const
