export const LOOKS_EVENTS = {
  LOOK_POST_PUBLISHED: 'LOOK_POST_PUBLISHED',
  LOOK_POST_LIKED: 'LOOK_POST_LIKED',
  LOOK_POST_COMMENTED: 'LOOK_POST_COMMENTED',
  LOOK_POST_SAVED: 'LOOK_POST_SAVED',
} as const

export type LooksEventName =
  (typeof LOOKS_EVENTS)[keyof typeof LOOKS_EVENTS]