// lib/looks/tagSlugParityFixture.ts
//
// Rendering + locating the committed parity fixture. Split from
// `tagSlugParity.ts` (which owns the cases) so the generator script, the drift
// test and the cross-repo guard all serialize it exactly one way.

import { deriveLookTagSlugParityCases } from './tagSlugParity'

/** Path of the committed fixture, relative to the repo root. */
export const LOOK_TAG_SLUG_FIXTURE_PATH = 'schema/parity/lookTagSlugs.json'

/** Path of tovis-ios's committed copy, relative to that repo's root. */
export const LOOK_TAG_SLUG_IOS_FIXTURE_PATH =
  'TovisTests/Fixtures/lookTagSlugs.json'

/**
 * Escape every non-ASCII code point as a `\uXXXX` sequence.
 *
 * 🔴 Load-bearing, not cosmetic. Several cases are DECOMPOSED (`e` followed by
 * U+0301) and exist precisely to distinguish that from the precomposed `é`.
 * Written as literal UTF-8, an editor, a linter or a `git` filter that
 * normalizes the file to NFC would silently merge the two — turning the
 * sharpest cases in the fixture into duplicates of their neighbours while every
 * test stayed green. Escaped, there is nothing left to normalize.
 *
 * The result is still ordinary JSON: `JSON.parse` and Foundation's JSONDecoder
 * both read the escapes back to the same string.
 */
function asciiOnly(json: string): string {
  return json.replace(
    /[-￿]/g,
    (ch) => '\\u' + ch.charCodeAt(0).toString(16).padStart(4, '0'),
  )
}

/**
 * The exact bytes of the committed fixture: a header naming what it is and
 * where it comes from, then the generated pairs. Trailing newline included.
 */
export function renderLookTagSlugFixture(): string {
  const body = {
    $comment:
      'GENERATED by `pnpm gen:look-tag-slug-fixture` from lib/looks/tags.ts ' +
      '(slugifyLookTag + resolveLookTagSlug). Do not hand-edit: ' +
      'lib/looks/tagSlugParity.test.ts fails when it drifts from the real ' +
      'functions. tovis-ios commits the same file at ' +
      'TovisTests/Fixtures/lookTagSlugs.json and drives LooksPath.tagSlug over ' +
      'every pair. Non-ASCII is escaped on purpose - some cases are decomposed.',
    cases: deriveLookTagSlugParityCases(),
  }
  return asciiOnly(JSON.stringify(body, null, 2)) + '\n'
}
