// lib/booking/constants.ts
export const MAX_SLOT_DURATION_MINUTES = 12 * 60
export const MAX_BOOKING_BUFFER_MINUTES = 180
export const DEFAULT_DURATION_MINUTES = 60
export const MAX_OTHER_OVERLAP_MINUTES =
  MAX_SLOT_DURATION_MINUTES + MAX_BOOKING_BUFFER_MINUTES