export type ConsultWriteErrorCode =
  | 'NOT_FOUND'
  | 'NOT_OWNER'
  | 'INVALID_REQUEST'
  | 'INVALID_STATE'
  | 'AGREEMENT_KIND_MISMATCH'
  | 'AGREEMENT_VERSION_MISMATCH'
  | 'AGREEMENTS_UNAVAILABLE'
  | 'AGREEMENTS_REQUIRED'
  | 'ALREADY_REVOKED'
  | 'PACK_VERSION_MISMATCH'
  | 'SCHEMA_VERSION_MISMATCH'
  | 'INVALID_ANSWERS'
  | 'IDEMPOTENCY_CONFLICT'
  | 'BOOKING_INELIGIBLE'
  | 'CAPTURE_PACK_VERSION_MISMATCH'
  | 'CAPTURE_SCHEMA_VERSION_MISMATCH'
  | 'CAPTURE_INVALID_SLOT'
  | 'CAPTURE_UPLOAD_EXPIRED'
  | 'CAPTURE_UPLOAD_MISMATCH'
  | 'CAPTURE_OBJECT_INVALID'
  | 'CAPTURE_QUALITY_UNAVAILABLE'
  | 'CAPTURE_QUALITY_FAILED'
  | 'CAPTURE_STORAGE_UNAVAILABLE'

export class ConsultWriteError extends Error {
  constructor(
    readonly code: ConsultWriteErrorCode,
    message: string,
  ) {
    super(message)
    this.name = 'ConsultWriteError'
  }
}
