export type ConsultWriteErrorCode =
  | 'NOT_FOUND'
  | 'NOT_OWNER'
  | 'INVALID_REQUEST'
  | 'INVALID_STATE'
  | 'AGREEMENT_KIND_MISMATCH'
  | 'AGREEMENT_VERSION_MISMATCH'
  | 'AGREEMENTS_UNAVAILABLE'
  | 'AGREEMENTS_REQUIRED'
  | 'ALREADY_REVOKED'
  | 'PACK_VERSION_MISMATCH'
  | 'SCHEMA_VERSION_MISMATCH'
  | 'INVALID_ANSWERS'
  | 'GOAL_DIRECTION_REQUIRED'
  | 'GOAL_DIRECTION_UNRESOLVED'
  | 'IDEMPOTENCY_CONFLICT'
  | 'BOOKING_INELIGIBLE'
  | 'CAPTURE_PACK_VERSION_MISMATCH'
  | 'CAPTURE_SCHEMA_VERSION_MISMATCH'
  | 'CAPTURE_INVALID_SLOT'
  | 'CAPTURE_UPLOAD_EXPIRED'
  | 'CAPTURE_UPLOAD_MISMATCH'
  | 'CAPTURE_OBJECT_INVALID'
  | 'CAPTURE_QUALITY_UNAVAILABLE'
  | 'CAPTURE_QUALITY_FAILED'
  | 'CAPTURE_QUALITY_LIMIT_EXCEEDED'
  | 'CAPTURE_STORAGE_UNAVAILABLE'
  | 'ANALYSIS_SCHEMA_VERSION_MISMATCH'
  | 'ANALYSIS_PROMPT_VERSION_MISMATCH'
  | 'ANALYSIS_PREREQUISITES_REQUIRED'
  | 'ANALYSIS_CAPTURES_REQUIRED'
  | 'ANALYSIS_INSPIRATION_REQUIRED'
  | 'ANALYSIS_UNAVAILABLE'
  | 'INSPIRATION_SCHEMA_VERSION_MISMATCH'
  | 'INSPIRATION_LOOK_UNAVAILABLE'
  | 'INSPIRATION_SOURCE_REQUIRED'
  | 'INSPIRATION_SOURCE_UNAVAILABLE'
  | 'INSPIRATION_UPLOAD_EXPIRED'
  | 'INSPIRATION_UPLOAD_MISMATCH'
  | 'INSPIRATION_OBJECT_INVALID'
  | 'INSPIRATION_STORAGE_UNAVAILABLE'
  | 'INSPIRATION_INVALID_ANSWER'
  | 'INSPIRATION_QUESTION_OUT_OF_ORDER'
  // P4, Stage 1. Two distinct failures, never one: UNAVAILABLE is the
  // provider (retry the same photo); UNREADABLE is this photograph (the
  // model named nothing at all, so ask for a clearer one). Part 0 rule 4
  // forbids either becoming a silent fall-back to the old question list.
  | 'INSPIRATION_ANALYSIS_UNAVAILABLE'
  | 'INSPIRATION_ANALYSIS_UNREADABLE'
  // Book the Look (B2): a look that cannot anchor a consult — no service
  // linkage, or a linkage outside the pilot vertical. `detail` names which.
  | 'LOOK_NOT_CONSULTABLE'

export class ConsultWriteError extends Error {
  constructor(
    readonly code: ConsultWriteErrorCode,
    message: string,
  ) {
    super(message)
    this.name = 'ConsultWriteError'
  }
}
